export const SESSION_LOAD_START = 'app/SESSION_LOAD_START'
export const SESSION_LOAD_FULFILLED = 'app/SESSION_LOAD_FULFILLED'

export const ACCESS_TOKEN_FETCH_START = 'app/ACCESS_TOKEN_FETCH_START'
export const ACCESS_TOKEN_FETCH_FULFILLED = 'app/ACCESS_TOKEN_FETCH_FULFILLED'
export const ACCESS_TOKEN_FETCH_REJECTED = 'app/ACCESS_TOKEN_FETCH_REJECTED'

export const ALERTS_FETCH_START = 'app/ALERTS_FETCH_START'
export const ALERTS_FETCH_FULFILLED = 'app/ALERTS_FETCH_FULFILLED'
export const ALERTS_FETCH_REJECTED = 'app/ALERTS_FETCH_REJECTED'

export const ALERTS_SAVE_START = 'app/ALERTS_SAVE_START'
export const ALERTS_SAVE_REJECTED = 'app/ALERTS_SAVE_REJECTED'
export const ALERTS_SAVE_FULFILLED = 'app/ALERTS_SAVE_FULFILLED'

export const STOCKS_FETCH_START = 'app/STOCKS_FETCH_START'
export const STOCKS_FETCH_FULFILLED = 'app/STOCKS_FETCH_FULFILLED'
export const STOCKS_FETCH_REJECTED = 'app/STOCKS_FETCH_REJECTED'
export const STOCKS_LOADED_FROM_DB = 'app/STOCKS_LOADED_FROM_DB'
