export const CANCEL_BUTTON_PRESSED = 'alert/CANCEL_BUTTON_PRESSED'
export const STOCK_SELECTED = 'alert/STOCK_SELECTED'
export const BACK_BUTTON_PRESSED = 'alert/BACK_BUTTON_PRESSED'

export const ALERT_SAVE_START = 'alert/ALERT_SAVE_START'
export const ALERT_SAVE_REJECTED = 'alert/ALERT_SAVE_REJECTED'
export const ALERT_SAVE_FULFILLED = 'alert/ALERT_SAVE_FULFILLED'
