export const CANCEL_BUTTON_PRESSED = 'alert/CANCEL_BUTTON_PRESSED'
export const STOCK_SELECTED = 'alert/STOCK_SELECTED'
export const BACK_BUTTON_PRESSED = 'alert/BACK_BUTTON_PRESSED'

export const SAVE_ALERT_START = 'alert/SAVE_ALERT_START'
export const SAVE_ALERT_FULFILLED = 'alert/SAVE_ALERT_FULFILLED'
